---

- name: Install Apache web server for RedHat derivatives
  yum: name={{ item }} state=present
  with_items:
   - httpd
  tags:
   - install
   - apache

- name: Start and enable Apache web server for RedHat derivatives
  service: name=httpd state=started enabled=yes
  tags:
   - install
   - apache
 
- name: Copy httpd.conf file
  copy: src=httpd.conf dest=/etc/httpd/conf/httpd.conf owner=root group=root mode=0644 backup=yes
  notify:
   - restart httpd
  tags:
   - configure
   - apache

- name: Set up virtual hosts
  template: src=vhosts.conf.j2 dest=/etc/httpd/conf.d/vhosts.conf
      owner=root group=root mode=0644
  notify:
   - restart httpd
  tags:
   - configure
   - apache
 
