---
# This playbook deploys the whole application stack in this site.  

- name: Apply common configuration to all nodes
  hosts: all

  roles:
    - role: ntp

- name: Deploy MySQL with root password with mediawiki user, password and database
  hosts: dbservers

  roles:
      - { role: mysql-server, 
          mysql_bind_address: "0.0.0.0",
          mysql_root_db_pass: mwiki_t3.A!,
          mysql_db: [{name: mwiki}], 
          mysql_users: [{
              name: mwiki_user, 
              pass: mwiki_t3.A!, 
              host: 192.168.50.11, 
              priv: "mwiki.*:ALL"
          }],
          mysql_repl_role: none
      } 

- name: configure and deploy the webservers and application code
  hosts: webservers

  roles:
    - role: mediawiki
    - { role: apache,
        apache_vhosts: [{
          servername: "mediawiki.dev",
          documentroot: "/var/www/html"
        }],
        apache_listen_ports: [ 80, ]
    }
