---
# This playbook deploys the whole application stack in this site.  

- name: apply common configuration to all nodes
  hosts: all
  user: root

  roles:
    - role: ntp

- name: deploy MySQL and configure the databases
  hosts: dbservers
  user: root

  roles:
    - { role: mysql-server, dbname: mwiki, dbuser: mwiki_user, upassword: mwiki_t3.A!} 

- name: configure and deploy the webservers and application code
  hosts: webservers
  user: root

  roles:
    - role: mediawiki

