---

- name: Download Mediawiki
  get_url: url=http://releases.wikimedia.org/mediawiki/1.22/mediawiki-1.22.5.tar.gz 
           dest=/tmp/mediawiki.tar.gz
           sha256sum="3acae43cb7859f5403c022f285d2281c41cf78a8b914777da5a049f8934cf722"

- name: Extract archive
  command: chdir=/var/www/html /bin/tar xvf /tmp/mediawiki.tar.gz creates=/var/www/html/mediawiki-1.22.5

- name: Change ownership of Mediawiki installation
  file: path=/var/www/html/mediawiki-1.22.5/ owner=apache group=apache state=directory recurse=yes

- name: Set up symlink to mediawiki
  command: chdir=/var/www /bin/ln -sf /var/www/html/mediawiki-1.22.5 /var/www/html/wiki 
           creates=/var/www/html/wiki

- name: Configure Mediawiki
  command: chdir=/var/www/html/wiki
           /usr/bin/php maintenance/install.php --dbserver 192.168.50.12 --dbname mwiki --dbuser mwiki_user --dbpass mwiki_t3.A! --dbtype mysql --pass wikipass --scriptpath /wiki wikitest wikiadmin 
           creates=/var/www/html/wiki/LocalSettings.php

- name: Test installation
  copy: src=test.py dest=/tmp/test.py
  notify: run tests

