---

- name: Download tarball
  get_url: url={{ mediawiki_downloadurl }}
           dest=/tmp/mediawiki.tar.gz
           sha256sum={{ mediawiki_sha256sum }}
  tags:
    - install
    - mediawiki

- name: Extract tarball
  command: chdir=/tmp /bin/tar xf /tmp/mediawiki.tar.gz 
           creates=/tmp/mediawiki-{{ mediawiki_version }}
  tags:
    - install
    - mediawiki

- name: Move extracted files to final location
  command: chdir=/tmp mv /tmp/mediawiki-{{ mediawiki_version }} {{ mediawiki_installpath }} 
           creates={{ mediawiki_installpath }}
  tags:
    - install
    - mediawiki
 
- name: Change ownership of Mediawiki installation
  file: path={{ mediawiki_installpath }} owner=apache group=apache state=directory recurse=yes
  tags:
    - install
    - mediawiki

- name: Configure Mediawiki
  command: chdir={{ mediawiki_installpath }} 
           /usr/bin/php maintenance/install.php --dbserver {{ mediawiki_db_host }} --dbname {{ mediawiki_db_name }} --dbuser {{ mediawiki_db_user }} --dbpass {{ mediawiki_db_pass }} --dbtype {{ mediawiki_db_type }} --pass {{ mediawiki_adm_pass }} --scriptpath {{ mediawiki_scriptpath }} {{ mediawiki_name }} {{ mediawiki_adm_user }}
           creates={{ mediawiki_installpath }}/LocalSettings.php
  tags:
    - configure
    - mediawiki

- name: Test installation
  copy: src=test.py dest=/tmp/test.py
  notify: run tests
  tags:
    - configure
    - mediawiki

