---

- name: install Postfix packages                                                               
  yum: name={{ item }} state=present
  with_items: postfix_packages
  tags:
    - install
    - postfix

- name: Copy Postfix main.cf config file
  template: src=main.cf.j2 dest=/etc/postfix/main.cf owner=root group=root mode=0744 backup=yes
  notify:
   - restart postfix
  tags:
   - configure
   - postfix

- name: Copy Postfix smtp_relay_credentials config file
  lineinfile: dest=/etc/postfix/smtp_relay_credentials line="[{{ postfix_relay_server_host }}]:587  {{ postfix_relay_server_user }}:{{ postfix_relay_server_password }}" state=present create=true owner=root group=root mode=0700
  when: postfix_relay
  notify:
   - restart postfix
  tags:
   - configure
   - postfix
 
