---

- name: install Postfix packages                                                               
  yum: name={{ item }} state=present
  with_items: postfix_packages
  tags:
    - install
    - postfix

- name: Copy Postfix main.cf config file
  template: src=main.cf.j2 dest=/etc/postfix/main.cf owner=root group=root mode=0644 backup=yes
  notify:
   - restart postfix
  tags:
   - configure
   - postfix

- name: Copy Postfix smtp_relay_credentials config file
  template: src=smtp_relay_credentials.j2 dest=/etc/postfix/smtp_relay_credentials owner=root group=root mode=0600
  when: postfix_relay
  notify:
   - update smtp_relay_credentials
   - restart postfix
  tags:
   - configure
   - postfix
 
