---

- name: Install monit
  yum: name={{ item }} state=present
  with_items: monit_packages
  tags:
    - install
    - monit

- name: Set up the monit daemon
  template: src=monit.conf.j2 dest=/etc/monit.conf
  tags:
    - configure
    - monit

