---

# Download tarball data
mediawiki_version: 1.22.5
mediawiki_downloadurl: "http://releases.wikimedia.org/mediawiki/1.22/mediawiki-{{ mediawiki_version }}.tar.gz"
mediawiki_sha256sum: 3acae43cb7859f5403c022f285d2281c41cf78a8b914777da5a049f8934cf722

# Installation parameters
mediawiki_installpath: /var/www/html/wiki
mediawiki_uploadpath: /var/www/data/wiki

# Database parameters
mediawiki_db_pass: dbPassword
mediawiki_db_user: dbUser
mediawiki_db_name: mwiki
mediawiki_db_host: localhost
mediawiki_db_type: mysql

# See php maintenance/install.php command for more info
# Setup parameters
mediawiki_scriptpath: /wiki
mediawiki_adm_user: wikiadmin
mediawiki_adm_pass: wikipass
mediawiki_name: mediawiki

mediawiki_paths_permissions: [
  { path: images, owner: apache, group: apache, mode: 700, recurse: false },
  { path: maintenance, owner: root, group: root, mode: 700, recurse: true }
] 
